---
LOGGING:
  version: 1

  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG

  formatters:
    default:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      class: logging.Formatter

  disable_existing_loggers: false

  root:
    level: DEBUG
    handlers: [console]

  loggers:
    aixm_graph:
      level: DEBUG

UPLOAD_FOLDER: /tmp

PAGE_LIMIT: 5

FEATURES:
  AerialRefuelling:
    abbrev: ARF
    color: '#f0f8ff'
    fields:
      concat: true
      names:
        - designatorPrefix
        - designatorNumber
        - designatorSuffix
        - designatorDirection
    shape: square
  AeronauticalGroundLight:
    abbrev: AGL
    color: '#efdecd'
    fields:
      names:
        - type
        - name
    shape: square
  AirTrafficControlService:
    abbrev: ATC
    color: '#f4c2c2'
    fields:
      names:
        - location
        - type
    shape: square
  AirTrafficManagementService:
    abbrev: ATM
    color: '#fae7b5'
    fields:
      names:
    shape: square
  AircraftGroundService:
    abbrev: ACG
    color: '#ffbf00'
    fields:
      names:
        - type
    shape: square
  AircraftStand:
    abbrev: AST
    color: '#a4c639'
    fields:
      names:
        - designator
        - type
    shape: square
  AirportClearanceService:
    abbrev: ACS
    color: '#cd9575'
    fields:
      names:
        - name
    shape: square
  AirportHeliport:
    abbrev: AHP
    color: '#faebd7'
    fields:
      names:
        - designator
    shape: square
  AirportHeliportCollocation:
    abbrev: AHC
    color: '#8db600'
    fields:
      names:
    shape: square
  AirportHotSpot:
    abbrev: AHT
    color: '#fbceb1'
    fields:
      names:
        - designator
    shape: square
  AirportProtectionAreaMarking:
    abbrev: APM
    color: '#7fffd4'
    fields:
      names:
    shape: square
  AirportSuppliesService:
    abbrev: ASV
    color: '#e9d66b'
    fields:
      names:
        - fuelSupply
        - oilSupply
        - nitrogenSupply
        - oxygenSupply
    shape: square
  Airspace:
    abbrev: ASE
    color: '#ff9966'
    fields:
      names:
        - designator
        - type
    shape: square
  AirspaceBorderCrossing:
    abbrev: ABC
    color: '#89cff0'
    fields:
      names:
    shape: square
  AltimeterSource:
    abbrev: ALT
    color: '#bcd4e6'
    fields:
      names:
    shape: square
  AngleIndication:
    abbrev: AIN
    color: '#f0ffff'
    fields:
      names:
    shape: square
  ApproachLightingSystem:
    abbrev: APL
    color: '#f0f8ff'
    fields:
      names:
    shape: hexagon
  Apron:
    abbrev: APN
    color: '#efdecd'
    fields:
      names:
        - name
    shape: hexagon
  ApronElement:
    abbrev: AEL
    color: '#ffbf00'
    fields:
      names:
        - type
    shape: hexagon
  ApronLightSystem:
    abbrev: ALS
    color: '#a4c639'
    fields:
      names:
        - color
    shape: hexagon
  ApronMarking:
    abbrev: AMK
    color: '#cd9575'
    fields:
      names:
    shape: hexagon
  ArrestingGear:
    abbrev: AGR
    color: '#faebd7'
    fields:
      names:
        - location
        - length
        - width
        - status
    shape: hexagon
  ArrivalFeederLeg:
    abbrev: AFL
    color: '#fbceb1'
    fields:
      names:
        - length
    shape: hexagon
  ArrivalLeg:
    abbrev: ARL
    color: '#8db600'
    fields:
      names:
        - length
    shape: hexagon
  AuthorityForAirspace:
    abbrev: AFA
    color: '#7fffd4'
    fields:
      names:
        - type
    shape: hexagon
  Azimuth:
    abbrev: AZM
    color: '#e9d66b'
    fields:
      names:
        - designator
        - type
    shape: hexagon
  ChangeOverPoint:
    abbrev: COP
    color: '#ff9966'
    fields:
      names:
    shape: hexagon
  CheckpointINS:
    abbrev: CNS
    color: '#89cff0'
    fields:
      names:
        - category
        - position
    shape: hexagon
  CheckpointVOR:
    abbrev: CVO
    color: '#f4c2c2'
    fields:
      names:
        - category
        - position
    shape: hexagon
  CirclingArea:
    abbrev: CIA
    color: '#fae7b5'
    fields:
      names:
    shape: hexagon
  DME:
    abbrev: DME
    color: '#cd9575'
    fields:
      names:
        - type
        - designator
    shape: diamond
  DeicingArea:
    abbrev: DAA
    color: '#bcd4e6'
    fields:
      names:
    shape: hexagon
  DeicingAreaMarking:
    abbrev: DAM
    color: '#f0ffff'
    fields:
      names:
    shape: hexagon
  DepartureLeg:
    abbrev: DLG
    color: '#f0f8ff'
    fields:
      names:
    shape: diamond
  DesignatedPoint:
    abbrev: DPN
    color: '#efdecd'
    fields:
      names:
        - designator
    shape: diamond
  DirectionFinder:
    abbrev: DFN
    color: '#ffbf00'
    fields:
      names:
    shape: diamond
  DistanceIndication:
    abbrev: DIN
    color: '#a4c639'
    fields:
      names:
    shape: diamond
  Elevation:
    abbrev: ELV
    color: '#faebd7'
    fields:
      names:
    shape: diamond
  FinalLeg:
    abbrev: FLG
    color: '#8db600'
    fields:
      names:
    shape: diamond
  FireFightingService:
    abbrev: FFS
    color: '#fbceb1'
    fields:
      names:
    shape: diamond
  FlightRestriction:
    abbrev: FRS
    color: '#7fffd4'
    fields:
      names:
    shape: diamond
  FloatingDockSite:
    abbrev: FGD
    color: '#e9d66b'
    fields:
      names:
    shape: diamond
  GeoBorder:
    abbrev: GBR
    color: '#ff9966'
    fields:
      names:
        - type
    shape: diamond
  Glidepath:
    abbrev: GPT
    color: '#89cff0'
    fields:
      names:
        - designator
    shape: diamond
  GroundTrafficControlService:
    abbrev: GTC
    color: '#f4c2c2'
    fields:
      names:
    shape: diamond
  GuidanceLine:
    abbrev: GLN
    color: '#fae7b5'
    fields:
      names:
        - type
        - designator
    shape: diamond
  GuidanceLineLightSystem:
    abbrev: GLL
    color: '#bcd4e6'
    fields:
      names:
    shape: diamond
  GuidanceLineMarking:
    abbrev: GLM
    color: '#f0ffff'
    fields:
      names:
    shape: diamond
  HoldingAssessment:
    abbrev: HAS
    color: '#f0f8ff'
    fields:
      names:
    shape: triangle
  HoldingPattern:
    abbrev: HPT
    color: '#efdecd'
    fields:
      names:
    shape: triangle
  InformationService:
    abbrev: ISV
    color: '#ffbf00'
    fields:
      names:
    shape: triangle
  InitialLeg:
    abbrev: ILG
    color: '#a4c639'
    fields:
      names:
    shape: triangle
  InstrumentApproachProcedure:
    abbrev: IAP
    color: '#cd9575'
    fields:
      names:
    shape: triangle
  IntermediateLeg:
    abbrev: INL
    color: '#faebd7'
    fields:
      names:
    shape: triangle
  Localizer:
    abbrev: LLZ
    color: '#8db600'
    fields:
      names:
        - designator
    shape: triangle
  MarkerBeacon:
    abbrev: MBC
    color: '#fbceb1'
    fields:
      names:
        - designator
    shape: triangle
  MarkingBuoy:
    abbrev: MKB
    color: '#7fffd4'
    fields:
      names:
        - type
        - designator
    shape: triangle
  MissedApproachLeg:
    abbrev: MAL
    color: '#e9d66b'
    fields:
      names:
    shape: triangle
  NDB:
    abbrev: NDB
    color: '#fae7b5'
    fields:
      names:
        - keys
    shape: triangle
  Navaid:
    abbrev: NAV
    color: '#ff9966'
    fields:
      names:
        - type
        - designator
    shape: triangle
  NavigationArea:
    abbrev: NAA
    color: '#89cff0'
    fields:
      names:
        - navigationAreaType
        - sector
    shape: triangle
  NavigationAreaRestriction:
    abbrev: NAN
    color: '#f4c2c2'
    fields:
      names:
        - type
    shape: triangle
  NonMovementArea:
    abbrev: NMA
    color: '#bcd4e6'
    fields:
      names:
    shape: triangle
  ObstacleArea:
    abbrev: OAR
    color: '#f0ffff'
    fields:
      names:
    shape: triangle
  OrganisationAuthority:
    abbrev: ORG
    color: '#f0f8ff'
    fields:
      names:
        - name
    shape: triangleDown
  PassengerLoadingBridge:
    abbrev: PLB
    color: '#efdecd'
    fields:
      names:
    shape: triangleDown
  PassengerService:
    abbrev: PSV
    color: '#ffbf00'
    fields:
      names:
    shape: triangleDown
  PilotControlledLighting:
    abbrev: PCG
    color: '#a4c639'
    fields:
      names:
    shape: triangleDown
  PrecisionApproachRadar:
    abbrev: PAR
    color: '#cd9575'
    fields:
      names:
    shape: triangleDown
  PrimarySurveillanceRadar:
    abbrev: PSR
    color: '#faebd7'
    fields:
      names:
        - location
    shape: triangleDown
  ProcedureDME:
    abbrev: PDM
    color: '#8db600'
    fields:
      names:
    shape: triangleDown
  RadioCommunicationChannel:
    abbrev: RCC
    color: '#fbceb1'
    fields:
      names:
    shape: triangleDown
  RadioFrequencyArea:
    abbrev: RFA
    color: '#7fffd4'
    fields:
      names:
        - type
    shape: triangleDown
  Road:
    abbrev: ROA
    color: '#e9d66b'
    fields:
      names:
        - designator
    shape: triangleDown
  Route:
    abbrev: RTE
    color: '#ff9966'
    fields:
      concat: true
      names:
        - designatorPrefix
        - designatorNumber
        - designatorSecondLetter
        - type
    shape: triangleDown
  RouteDME:
    abbrev: RDM
    color: '#89cff0'
    fields:
      names:
    shape: triangleDown
  RouteSegment:
    abbrev: RSG
    color: '#f4c2c2'
    fields:
      names:
    shape: triangleDown
  RulesProcedures:
    abbrev: RUP
    color: '#fae7b5'
    fields:
      names:
    shape: triangleDown
  Runway:
    abbrev: RWY
    color: '#bcd4e6'
    fields:
      names:
        - designator
        - type
    shape: triangleDown
  RunwayBlastPad:
    abbrev: RBP
    color: '#f0ffff'
    fields:
      names:
    shape: triangleDown
  RunwayCentrelinePoint:
    abbrev: RCP
    color: '#f0f8ff'
    fields:
      names:
        - designator
    shape: ellipse
  RunwayDirection:
    abbrev: RDN
    color: '#efdecd'
    fields:
      names:
        - designator
    shape: ellipse
  RunwayDirectionLightSystem:
    abbrev: RLS
    color: '#ffbf00'
    fields:
      names:
    shape: ellipse
  RunwayElement:
    abbrev: REL
    color: '#a4c639'
    fields:
      names:
    shape: ellipse
  RunwayMarking:
    abbrev: RMG
    color: '#cd9575'
    fields:
      names:
    shape: ellipse
  RunwayProtectArea:
    abbrev: RPA
    color: '#faebd7'
    fields:
      names:
        - type
    shape: ellipse
  RunwayProtectAreaLightSystem:
    abbrev: RPL
    color: '#8db600'
    fields:
      names:
    shape: ellipse
  RunwayVisualRange:
    abbrev: RVR
    color: '#fbceb1'
    fields:
      names:
    shape: ellipse
  SDF:
    abbrev: SDF
    color: '#e9d66b'
    fields:
      names:
        - designator
    shape: ellipse
  SafeAltitudeArea:
    abbrev: SAA
    color: '#7fffd4'
    fields:
      names:
    shape: ellipse
  SeaplaneLandingArea:
    abbrev: SLA
    color: '#ff9966'
    fields:
      names:
    shape: ellipse
  SeaplaneRampSite:
    abbrev: SPR
    color: '#89cff0'
    fields:
      names:
    shape: ellipse
  SearchRescueService:
    abbrev: SRE
    color: '#f4c2c2'
    fields:
      names:
        - type
    shape: ellipse
  SecondarySurveillanceRadar:
    abbrev: SSV
    color: '#fae7b5'
    fields:
      names:
    shape: ellipse
  SignificantPointInAirspace:
    abbrev: SPA
    color: '#bcd4e6'
    fields:
      names:
    shape: ellipse
  SpecialDate:
    abbrev: SPD
    color: '#f0ffff'
    fields:
      names:
    shape: ellipse
  SpecialNavigationStation:
    abbrev: SNS
    color: '#f0f8ff'
    fields:
      names:
    shape: dot
  SpecialNavigationSystem:
    abbrev: SNY
    color: '#efdecd'
    fields:
      names:
        - designator
        - type
    shape: dot
  StandMarking:
    abbrev: SMK
    color: '#fbceb1'
    fields:
      names:
    shape: dot
  StandardInstrumentArrival:
    abbrev: SIA
    color: '#ffbf00'
    fields:
      names:
        - designator
    shape: dot
  StandardInstrumentDeparture:
    abbrev: SID
    color: '#a4c639'
    fields:
      names:
        - designator
    shape: dot
  StandardLevelColumn:
    abbrev: SLC
    color: '#cd9575'
    fields:
      names:
    shape: dot
  StandardLevelSector:
    abbrev: SLS
    color: '#faebd7'
    fields:
      names:
    shape: dot
  StandardLevelTable:
    abbrev: SLB
    color: '#8db600'
    fields:
      names:
    shape: dot
  SurveyControlPoint:
    abbrev: SCP
    color: '#7fffd4'
    fields:
      names:
        - designator
    shape: dot
  TACAN:
    abbrev: TCN
    color: '#e9d66b'
    fields:
      names:
        - designator
    shape: dot
  TaxiHoldingPosition:
    abbrev: THP
    color: '#ff9966'
    fields:
      names:
    shape: dot
  TaxiHoldingPositionLightSystem:
    abbrev: THL
    color: '#89cff0'
    fields:
      names:
    shape: dot
  TaxiHoldingPositionMarking:
    abbrev: THM
    color: '#f4c2c2'
    fields:
      names:
    shape: dot
  Taxiway:
    abbrev: TWY
    color: '#fae7b5'
    fields:
      names:
        - designator
        - type
    shape: dot
  TaxiwayElement:
    abbrev: TWE
    color: '#bcd4e6'
    fields:
      names:
        - type
    shape: dot
  TaxiwayLightSystem:
    abbrev: TWL
    color: '#f0ffff'
    fields:
      names:
    shape: dot
  TaxiwayMarking:
    abbrev: TWM
    color: '#f0f8ff'
    fields:
      names:
    shape: box
  TerminalArrivalArea:
    abbrev: TAA
    color: '#efdecd'
    fields:
      names:
    shape: box
  TouchDownLiftOff:
    abbrev: TLA
    color: '#ffbf00'
    fields:
      names:
        - designator
    shape: box
  TouchDownLiftOffLightSystem:
    abbrev: TLS
    color: '#a4c639'
    fields:
      names:
    shape: box
  TouchDownLiftOffMarking:
    abbrev: TLM
    color: '#cd9575'
    fields:
      names:
    shape: box
  TouchDownLiftOffSafeArea:
    abbrev: TSA
    color: '#faebd7'
    fields:
      names:
    shape: box
  Unit:
    abbrev: UNI
    color: '#8db600'
    fields:
      names:
        - designator
        - type
    shape: box
  UnplannedHolding:
    abbrev: UHG
    color: '#fbceb1'
    fields:
      names:
    shape: box
  VOR:
    abbrev: VOR
    color: '#ff9966'
    fields:
      names:
        - designator
        - type
    shape: box
  VerticalStructure:
    abbrev: VST
    color: '#7fffd4'
    fields:
      names:
    shape: box
  VisualGlideSlopeIndicator:
    abbrev: VGI
    color: '#e9d66b'
    fields:
      names:
        - type
    shape: box
  WorkArea:
    abbrev: WAR
    color: '#89cff0'
    fields:
      names:
    shape: box
