name: aixm-graph
dependencies:
  - _libgcc_mutex=0.1=main
  - atomicwrites=1.3.0=py37_1
  - attrs=19.3.0=py_0
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - click=7.1.1=py_0
  - coverage=5.0=py37h7b6447c_0
  - flask=1.1.1=py_1
  - flask-cors=3.0.8=py_0
  - gunicorn=20.0.4=py37_0
  - icu=58.2=h9c2bf20_1
  - importlib_metadata=1.5.0=py37_0
  - itsdangerous=1.1.0=py_0
  - jinja2=2.11.1=py_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libxml2=2.9.9=hea5a465_1
  - libxslt=1.1.33=h7d1a2b0_0
  - lxml=4.5.0=py37hefd8a0e_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - more-itertools=8.2.0=py_0
  - ncurses=6.2=he6710b0_0
  - openssl=1.1.1f=h7b6447c_0
  - packaging=20.3=py_0
  - pip=20.0.2=py37_1
  - pluggy=0.13.1=py37_0
  - py=1.8.1=py_0
  - pyparsing=2.4.6=py_0
  - pytest=5.0.1=py37_0
  - pytest-cov=2.8.1=py_0
  - python=3.7.7=hcf32534_0_cpython
  - pyyaml=5.3.1=py37h7b6447c_0
  - readline=8.0=h7b6447c_0
  - setuptools=46.1.3=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wcwidth=0.1.9=py_0
  - werkzeug=1.0.1=py_0
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.1.7=had09818_2
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h7b6447c_3
